{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"public id_date\",\"public id_cac\",\"public balance_diario\",\"public inv_cif_fenacoac\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.1102.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 9/08/2020 22:39:27.",
        "folder": "Query Errors - 9/08/2020 22:39:27"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "Errors in queries that were loaded on 12/08/2020 21:37:52.",
        "folder": "Query Errors - 12/08/2020 21:37:52"
      }
    ],
    "relationships": [
      {
        "name": "43e82357-aca6-4b9c-a1ff-165b7d1b25c6",
        "fromColumn": "cac",
        "fromTable": "public balance_diario",
        "toColumn": "id_cac_2",
        "toTable": "public id_cac"
      },
      {
        "name": "4ec78a7c-7beb-4b60-9170-8b5dd98476c5",
        "fromColumn": "id_date",
        "fromTable": "public id_date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ed1405b5-aff4-4ab9-86f5-6a9f7b3c8e91"
      },
      {
        "name": "e2313134-add7-4c25-8667-d2a72fe2a9e0",
        "fromColumn": "fecha",
        "fromTable": "public balance_diario",
        "toColumn": "id_date",
        "toTable": "public id_date"
      },
      {
        "name": "b4b4e953-e38c-420d-b907-4696f2fb51af",
        "fromColumn": "id_cac",
        "fromTable": "public inv_cif_fenacoac",
        "toColumn": "id_cac_2",
        "toTable": "public id_cac"
      },
      {
        "name": "50ef6713-c571-473f-a3e1-30085af8d0b2",
        "fromColumn": "last_year",
        "fromTable": "public id_date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4de526aa-4797-431a-8d4c-a560e85dc302"
      }
    ],
    "roles": [
      {
        "name": "Cooperativa",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e2c095e0049e4eadb1ad8a2e28d3c12f"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "public id_cac",
            "filterExpression": "[Categoria] = \"SISTEMA MICOOPE\""
          }
        ]
      },
      {
        "name": "All",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "23895135374b404d8b8b3da6f3e54dd2"
          }
        ],
        "modelPermission": "read"
      },
      {
        "name": "Fenacoac",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "28a7cdfc0441439a8c214f7d90cd025c"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "public id_cac",
            "filterExpression": "[Categoria] = \"CORPORATIVO\""
          }
        ]
      }
    ],
    "sourceQueryCulture": "es-GT",
    "tables": [
      {
        "name": "DateTableTemplate_2f549d59-6ace-455f-8bbb-9687ed6c1c12",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0fc7c86c-a59e-4a53-8c3a-e169fb9d15b9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a13125bd-7948-45dd-908d-387dae2f9f33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c24f7988-e839-42ff-8caa-c286af012ac6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "84932f1d-c30a-4c8d-a5d0-0fccaaa4acfa",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0c4dfcad-bcde-4e80-813d-4e36a58fa6b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9e02352f-b69c-484d-8de7-69ce39f2c088",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cc7b0921-201a-4ce0-b434-2708c3622218",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bdbecaad-2d0c-44a2-9633-28fedefe0256",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "494001bc-c681-4864-ac56-f128c4231d26",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4b36181e-f34b-4c7a-a01c-e2996a01ea7f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "665fda8b-66b4-49bc-a680-8aa3791c62f1",
                "ordinal": 3
              }
            ],
            "lineageTag": "7e18435b-7531-4fe7-83d1-7665be1d6806"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "15df9896-5066-466a-8eef-da66685216c9",
        "partitions": [
          {
            "name": "DateTableTemplate_2f549d59-6ace-455f-8bbb-9687ed6c1c12-ef941633-cc0a-40bb-b29e-dd50eb8be6c6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "public id_date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "id_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "d \"de\" mmmm",
            "lineageTag": "c833747e-60f3-452a-829c-af6d96bc998f",
            "sourceColumn": "id_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ed1405b5-aff4-4ab9-86f5-6a9f7b3c8e91"
                },
                "isDefault": true,
                "relationship": "4ec78a7c-7beb-4b60-9170-8b5dd98476c5"
              }
            ]
          },
          {
            "name": "month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "083c734e-11c9-4d1e-8f54-8a1f514bfcc3",
            "sourceColumn": "month",
            "summarizeBy": "none"
          },
          {
            "name": "last_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm \"de\" yyyy",
            "lineageTag": "c0c02738-e7a0-4d37-a94a-6f96954adf61",
            "sourceColumn": "last_year",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4de526aa-4797-431a-8d4c-a560e85dc302"
                },
                "isDefault": true,
                "relationship": "50ef6713-c571-473f-a3e1-30085af8d0b2"
              }
            ]
          },
          {
            "name": "mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ff7af90-c2b1-40d7-b01e-dd0145d13878",
            "sourceColumn": "mes",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "id_date Hierarchy",
            "levels": [
              {
                "name": "id_date",
                "column": "id_date",
                "lineageTag": "15b84cd2-d0db-4efb-b27a-0e922bab56aa",
                "ordinal": 0
              }
            ],
            "lineageTag": "25abbc5e-9477-42c2-9259-f333fbfd6e30"
          }
        ],
        "lineageTag": "2ed32041-a88f-4d6a-b48b-d1cc80500064",
        "partitions": [
          {
            "name": "public id_date-9cb24c7b-9cd6-4e03-9d30-861cbfb3478a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"10.138.30.11\", \"MICOOPE_BI\"),",
                "    dbo_key_date_d = Source{[Schema=\"dbo\",Item=\"key_date_d\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_key_date_d,{{\"id_date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "public id_cac",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "id_cac_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1de6cc1e-d001-490a-9a9c-81485273b3fe",
            "sourceColumn": "id_cac_2",
            "summarizeBy": "none"
          },
          {
            "name": "id_cac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95ab2feb-58a0-4e78-9435-9d64b4891118",
            "sourceColumn": "id_cac",
            "summarizeBy": "sum"
          },
          {
            "name": "Cooperativa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b828a34-d84a-4cf0-94a0-7f61e626df1e",
            "sourceColumn": "Cooperativa",
            "summarizeBy": "none"
          },
          {
            "name": "Tamaño",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f8af21f4-4eb4-472c-b622-d55aeafe201f",
            "sourceColumn": "Tamaño",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "398dd296-14ad-4c21-bac9-8adb72ca3b6c",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e60655d5-cf54-46ef-a6ec-16dbe757b357",
            "sourceColumn": "Categoria",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1d69b046-9949-48bd-9a72-988939325286",
        "partitions": [
          {
            "name": "public id_cac-049d2e04-6783-4c58-a572-3c7b4cd9c57d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"10.138.30.11\", \"MICOOPE_BI\"),",
                "    dbo_key_cac = Source{[Schema=\"dbo\",Item=\"key_cac\"]}[Data]",
                "in",
                "    dbo_key_cac"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "public balance_diario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "fecha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "d/mm/yyyy",
            "lineageTag": "00f346b8-2687-41f2-bef6-dbd9ba2cf905",
            "sourceColumn": "fecha",
            "summarizeBy": "none"
          },
          {
            "name": "cac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "663128e2-41a2-4a6c-bc1d-ba3be6ab510d",
            "sourceColumn": "cac",
            "summarizeBy": "none"
          },
          {
            "name": "nivel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7b53aebc-4879-41c2-8edd-17f09d0939e3",
            "sourceColumn": "nivel",
            "summarizeBy": "sum"
          },
          {
            "name": "cuenta_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "73d03549-2a51-4601-b13a-0b92dbcbb625",
            "sourceColumn": "cuenta_id",
            "summarizeBy": "none"
          },
          {
            "name": "cuenta_nom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d560346e-c336-44d9-b9b8-d1b1b0cd0dbf",
            "sourceColumn": "cuenta_nom",
            "summarizeBy": "none"
          },
          {
            "name": "agencia_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "37b1cea5-ee3e-4be1-bb5e-28addc79120f",
            "sourceColumn": "agencia_id",
            "summarizeBy": "sum"
          },
          {
            "name": "agencia_nom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce365e66-0b70-4819-9c55-dbd883f7dd0a",
            "sourceColumn": "agencia_nom",
            "summarizeBy": "none"
          },
          {
            "name": "saldo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "cc64835e-e2c8-4816-ab49-e183a077d7f2",
            "sourceColumn": "saldo",
            "summarizeBy": "sum"
          },
          {
            "name": "nombre_completo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'public balance_diario'[cuenta_id] & \" \" & 'public balance_diario'[cuenta_nom]",
            "isDataTypeInferred": true,
            "lineageTag": "a62a165b-fde2-4312-897b-bc7a6c72823d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "fecha_titulo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "DAY('public balance_diario'[fecha]) & \" - \" & MONTH('public balance_diario'[fecha])",
            "isDataTypeInferred": true,
            "lineageTag": "5837bbc6-a8d2-4dbc-a1be-110a143b6d92",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "d5582d5b-d94f-4531-b2d8-116d30dc7664",
        "measures": [
          {
            "name": "Prueba Acida",
            "expression": "ABS((CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"101\")+CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"305\"))/((CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"301102\")+CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"301103\")+CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"301106\"))))",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "f25fe2ba-8ebd-4fdd-b5d1-03a8f04879db"
          },
          {
            "name": "E2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"101\")/((CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"1\"))+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"2\")))",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "28d9a993-1f72-43a3-a08a-f328a9a505a8"
          },
          {
            "name": "saldo_abs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "ABS(SUM('public balance_diario'[saldo]))",
            "formatString": "#,0",
            "lineageTag": "ea247c65-6e30-4e2f-b6bd-e33aa38309a9"
          },
          {
            "name": "ACTIVO TOTAL",
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"1\")+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"2\"))",
            "formatString": "#,0.0",
            "lineageTag": "69e5f67d-6282-4bc5-bed9-465eb1f29d99"
          },
          {
            "name": "OTROS INGRESOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"602\")+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"604\"))+CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"605\")+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"607\"))+CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"612\"))*-1",
            "formatString": "#,0",
            "lineageTag": "cef0a7d6-d85d-4899-940e-a9b62b355cd6"
          },
          {
            "name": "OTROS GASTOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"703\")+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"704\"))+CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"708\")",
            "formatString": "#,0",
            "lineageTag": "6e5d6b12-c8ac-4c0f-a23d-d8e38c47930d"
          },
          {
            "name": "RESULTADO EJERCICIO",
            "expression": "(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"6\")+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"7\")))*-1",
            "formatString": "#,0.0",
            "lineageTag": "f822f295-920f-4298-9891-39c8288a530f"
          },
          {
            "name": "E1 Prestamos Netos/AT",
            "expression": "(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"103\")+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"201103\")))/((CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"1\"))+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"2\")))",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "7c32e7b2-4ea7-4b22-a780-93ce8a1b71c2"
          },
          {
            "name": "E3",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"102\") - (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"102199\")) + (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"106\"))) /((CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"1\"))+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"2\")))",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "2c276e55-74be-4754-9e90-2634cfdc8020"
          },
          {
            "name": "E5",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[CAPTACIONES]/((CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"1\"))+(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"2\")))",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "95a8ee97-248b-4522-8767-f979cb2f61cf"
          },
          {
            "name": "CAPTACIONES",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "((CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"301\")) + (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"499\")))*-1",
            "lineageTag": "dd9f2131-60e5-4619-8d58-efc861b4d79e"
          },
          {
            "name": "APORTACIONES",
            "expression": "(CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"501\"))*-1",
            "formatString": "0.0",
            "lineageTag": "102d4a77-383e-4290-9c69-a37abb2289e9"
          },
          {
            "name": "CAPITAL INSTITUCIONAL",
            "expression": "(CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"503\"))*-1",
            "formatString": "0.0",
            "lineageTag": "ba48f663-a8b8-47ed-b2ad-7624def3eb5a"
          },
          {
            "name": "PRESTAMOS NETOS",
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"103\")+(CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"201103\"))",
            "formatString": "0.0",
            "lineageTag": "1e0e446a-d7dd-4d71-86fb-aefb7dcbcae8"
          },
          {
            "name": "DISPONIBILIDADES",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"101\")",
            "formatString": "#,0",
            "lineageTag": "b254d029-50bd-4059-b200-5d782485655f"
          },
          {
            "name": "INVERSIONES",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"102\")",
            "formatString": "#,0",
            "lineageTag": "2a01cb1e-5239-4834-8b4e-2dd200610857"
          },
          {
            "name": "E2 OPTIMO GTQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([ACTIVO TOTAL]*0.14)",
            "formatString": "#,0",
            "lineageTag": "259ec957-ebb1-4223-bd4b-56b05931e12d"
          },
          {
            "name": "E2 OPTIMO %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([E2 OPTIMO GTQ])/CALCULATE([ACTIVO TOTAL])",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "4a44ba1d-2f32-4709-9773-c8787b7bf7db"
          },
          {
            "name": "SUFICIENCIA O INSUFICIENCIA",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([DISPONIBILIDADES]-CALCULATE([E2 OPTIMO GTQ]))",
            "formatString": "#,0",
            "lineageTag": "ccee4c91-880b-47e5-861e-772f546c83c0"
          },
          {
            "name": "VARIACIÓN E2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([E2]-[E2 OPTIMO %])",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "1142b312-bd28-4abc-a38a-a09e521e79f6"
          },
          {
            "name": "TODAY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),DATEADD('public id_date'[id_date],0,DAY))",
            "formatString": "#,0",
            "lineageTag": "1ef0c523-aa20-4f8a-b1e8-b1895f4650e1"
          },
          {
            "name": "YESTERDAY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(sum('public balance_diario'[saldo]),DATEADD('public id_date'[id_date],-1,DAY))",
            "formatString": "#,0",
            "lineageTag": "0dc971f0-d767-4fdc-9ec9-0d1e6d49383d"
          },
          {
            "name": "DIFERENCIA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[TODAY]-[YESTERDAY]",
            "formatString": "#,0",
            "lineageTag": "9235208e-576a-43bb-90fe-a1173c691d41"
          },
          {
            "name": "PERÍODO ANTERIOR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('public balance_diario'[saldo]),DATESINPERIOD('public id_date'[id_date],DATE(2020,12,31),1,DAY))",
            "lineageTag": "28b56973-fd7f-4245-9a5c-6af92e73f539"
          },
          {
            "name": "dias_diff",
            "expression": "DATEDIFF(FIRSTDATE('public id_date'[last_year]),FIRSTDATE('public id_date'[id_date]),DAY)",
            "formatString": "0",
            "lineageTag": "27f0e8b4-8bff-4de7-8fff-14e7c9a6491e"
          },
          {
            "name": "activo_diciembre_anterior",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "(CALCULATE([ACTIVO TOTAL],DATEADD(FIRSTDATE('public id_date'[id_date]),[dias_diff]*-1,DAY)))",
            "formatString": "#,0",
            "lineageTag": "c2f58b3f-c43a-4e46-8abf-9d1465ac18ca"
          },
          {
            "name": "6_7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(ABS(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"6\"))-(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"7\")))",
            "lineageTag": "8460e210-7674-4ae5-8586-a1b886cd9533"
          },
          {
            "name": "E9",
            "expression": "((ABS(CALCULATE(sum('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"503\")))+(abs(CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"504103\")))+'public balance_diario'[6_7])/[ACTIVO TOTAL]",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "51e3613b-f6bd-4ecb-9241-7b44ed369224"
          },
          {
            "name": "R9",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "((((CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"706\"))-(CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"706103\")))/(([ACTIVO TOTAL]+[activo_diciembre_anterior])/2))/('public balance_diario'[dias_diff]))*360",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "f465ba69-4000-4f64-b8cf-fd8f36f7cd4e"
          },
          {
            "name": "R12",
            "expression": "((('public balance_diario'[6_7])/(([ACTIVO TOTAL]+[activo_diciembre_anterior])/2))/('public balance_diario'[dias_diff]))*360",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "e1288b70-4eb1-4892-ab06-16994caff16d"
          },
          {
            "name": "VARIACIÓN",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "[DIFERENCIA]/[YESTERDAY]",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "29ff175b-5fbc-4ced-9f97-694d3d116e2a"
          },
          {
            "name": "PRESTAMOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"103\")) - (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"103199\"))",
            "lineageTag": "75838f35-6a29-49f6-a6e7-e4fe6d97539d"
          },
          {
            "name": "INVERSIONES 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"102\")) - (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"102199\")) - (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"102699\"))",
            "lineageTag": "a31e64e4-dca5-440c-94d1-eddf26c6030d"
          },
          {
            "name": "CAPITAL INSTITUCIONAL 2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "((CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"503\")) + (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"504\")) + (CALCULATE(SUM('public balance_diario'[saldo]),'public balance_diario'[cuenta_id]==\"505\")))*-1",
            "lineageTag": "4fbd51c9-7fc7-4b6c-bc89-100241c882c7"
          },
          {
            "name": "E2 MINIMO %",
            "expression": "0.125",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "bc9eac2a-3102-4556-8b69-dd68e0a5a9e4"
          },
          {
            "name": "SUFICIENCIA / INSUFICIENCIA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE([DISPONIBILIDADES]-CALCULATE([E2 MINIMO GTQ]))",
            "formatString": "#,0",
            "lineageTag": "54ed931c-a12a-4119-b27c-8fb4db3a7acf"
          },
          {
            "name": "E2 MINIMO GTQ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE([ACTIVO TOTAL]*0.125)",
            "formatString": "#,0",
            "lineageTag": "35190aa2-1f57-4a67-8051-cab759151086"
          },
          {
            "name": "VARIACIÓN E2 MINIMO",
            "expression": "CALCULATE([E2]-[E2 MINIMO %])",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "3dda0050-0b39-45a3-95e6-bf6e7d0df700"
          }
        ],
        "partitions": [
          {
            "name": "public balance_diario-e60a06be-f52c-4451-9d2f-66d75bf62b59",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"10.138.30.11\", \"MICOOPE_BI\"),",
                "    dbo_bal_d = Source{[Schema=\"dbo\",Item=\"bal_d\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_bal_d,{{\"fecha\", type date}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type\", {\"saldo\"}),",
                "    #\"Removed Errors1\" = Table.RemoveRowsWithErrors(#\"Removed Errors\", {\"fecha\"})",
                "in",
                "    #\"Removed Errors1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ed1405b5-aff4-4ab9-86f5-6a9f7b3c8e91",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "88b1c7cf-86dd-4fc4-b45b-fc78231ee528",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "badb305b-877d-4029-b940-9d002721875b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7dc37e88-e66d-49e1-8a79-47eef3a6c788",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "24e33911-9cc4-4962-9b14-c314b09ae81d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "276536e9-c618-4958-8a0d-afde9d815108",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "116fb1f2-3b6c-44d9-a540-78823a29651a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7810b6f6-964a-45e6-a033-949028983858",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e613f943-7de2-4c46-8caf-3cf57845ee35",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "218b68a1-400c-4d1e-9019-68aa2c5f72bd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "40706297-d927-45ec-9ab1-e8671b26a525",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b08690ef-5a32-4482-abe4-044465f8ca5e",
                "ordinal": 3
              }
            ],
            "lineageTag": "adac76d9-70dc-4249-9baf-e4b66479c3d6"
          }
        ],
        "isHidden": true,
        "lineageTag": "e91ce21f-db22-4ba6-90b9-ab0604e86c2e",
        "partitions": [
          {
            "name": "LocalDateTable_ed1405b5-aff4-4ab9-86f5-6a9f7b3c8e91-0b2cbbdb-d8d1-464a-8b20-78e212c53a17",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('public id_date'[id_date])), 1, 1), Date(Year(MAX('public id_date'[id_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "public inv_cif_fenacoac",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "cif_fenacoac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2d56d23-dbe5-4884-947b-a6ba0ce7a800",
            "sourceColumn": "cif_fenacoac",
            "summarizeBy": "sum"
          },
          {
            "name": "nombre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f10d45b-1ac8-4bff-9309-1ffa24e0b8a3",
            "sourceColumn": "nombre",
            "summarizeBy": "none"
          },
          {
            "name": "id_cac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36394554-cdc0-429b-82a3-b5b314b3b2f7",
            "sourceColumn": "id_cac",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ab567df1-6b24-4fad-b271-861edbcbb6e6",
        "partitions": [
          {
            "name": "public inv_cif_fenacoac-bd7db77b-783f-4935-9b4a-4849dd6e2874",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"10.138.30.11\", \"MICOOPE_BI\"),",
                "    dbo_inv_cif_fenacoac = Source{[Schema=\"dbo\",Item=\"inv_cif_fenacoac\"]}[Data]",
                "in",
                "    dbo_inv_cif_fenacoac"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4de526aa-4797-431a-8d4c-a560e85dc302",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9a40e25c-b5e7-48ed-823f-5907a27619e1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "09ca8c74-da47-48ec-bde5-275720ec721e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a786e1e7-1390-42df-9c4f-e6e57c8c4031",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3a5a9ba2-e2ab-40fe-a88e-6e2f4f1eaa27",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "048e92ef-81cd-4e1d-b1bd-14a8fb902930",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e97aa3bd-79aa-4456-8def-8b3428d7ec2d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e6709423-eb3a-4276-b6e2-0433bcb3ee2d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "17546d76-64f6-423d-8f8e-9727ddabe479",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f6e42ed1-67b9-436f-a599-1839d313428e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3a49eb41-55e3-41f7-ae7c-bf1e8de537a1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2d5a4314-5efc-4941-b543-29f9aed19f9e",
                "ordinal": 3
              }
            ],
            "lineageTag": "c9024a63-6f8a-485c-88c9-3cf0b49f4fd2"
          }
        ],
        "isHidden": true,
        "lineageTag": "efd80d01-f4a9-4578-be5d-1deadc12204a",
        "partitions": [
          {
            "name": "LocalDateTable_4de526aa-4797-431a-8d4c-a560e85dc302-f642e4dd-335c-4786-a8c1-30198f7b93a5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('public id_date'[last_year])), 1, 1), Date(Year(MAX('public id_date'[last_year])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}